# fly.toml app configuration file generated for clienttutorialdeploy on 2025-09-19T09:43:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'clienttutorialdeploy'
primary_region = 'arn'

[build]

[env]
BACKEND_URL = "https://server-divine-grass-593.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
